  
version: '3'
services:
  web:
    build: ./
    ports:
      - 8080:80
    container_name: nginx
    volumes:
      - jjtech-volume:/opt
    networks:
      - frontier
      - backtier

  mysql:
    image: mysql
    ports: 
      - 3306
    container_name: mysql
    volumes:
      - data:/var/lib/mysql
    networks:
      - backtier

networks: 
  frontier:
  backtier:
volumes:
  jjtech-volume:
  data:

  